#!/usr/bin/env python3
"""Generate reports/index.html — a master landing page that links every
report in reports/ grouped by report type.

Naming convention drives grouping: a file's prefix up to the first
'_<sometoken>' that looks like a model name or scenario id determines
its section. Anything that doesn't match a known prefix is bucketed
into "Other".

Run after generating any new report:
    python make_index.py
"""

import html as _html
import re
from pathlib import Path

REPORTS_DIR = Path(__file__).resolve().parent / "reports"

# (prefix, section title, one-line description)
GROUPS = [
    ("consensus_summary_",
     "Consensus summaries",
     "Per-model internal consensus vs non-consensus and cross-model "
     "agreement on consensus scenarios."),
    ("cross_model_",
     "Cross-model galleries",
     "Side-by-side 5×3 heatmaps for scenarios where either model is "
     "internally contested or the two models disagree on verdict, with "
     "paired per-cell explanations."),
    ("contested_gallery_",
     "Contested-scenario galleries (single model)",
     "5×3 heatmap per contested scenario for one model, with "
     "per-cell explanation tables."),
    ("variant_trends_",
     "Variant trend (15×15 similarity) reports",
     "Pairwise-agreement and Spearman-correlation matrices across the "
     "15 race × income variants. Toggle plots 1 and 2 in the header."),
    ("misalignment_",
     "Misalignment-from-consensus reports",
     "Per-group leave-one-out distance from the consensus yes-rate, "
     "ranked by signed bias."),
    ("scenario_pair_",
     "Scenario-pair comparisons",
     "Two related scenarios viewed side-by-side."),
    ("scenario_report_",
     "Single-scenario reports",
     "Detail report for a single scenario."),
]


def esc(v) -> str:
    return _html.escape(str(v) if v is not None else "")


def humanize(name: str, prefix: str) -> str:
    """Strip the group prefix and the .html suffix; lightly format the rest."""
    stem = name[len(prefix):].removesuffix(".html")
    # numeric scenario-id ranges look nicer with a unicode dash
    stem = re.sub(r"_(\d{5})-(\d{5})", r" · scenarios \1–\2", stem)
    stem = re.sub(r"_00001_00136-00500", " · scenarios 00001+00136–00500", stem)
    stem = re.sub(r"_vs_", " vs ", stem)
    stem = re.sub(r"_explain-yes\b", " · explain-yes", stem)
    stem = re.sub(r"_explain-no\b", " · explain-no", stem)
    stem = re.sub(r"_axis-(race|income)\b", r" · axis=\1", stem)
    stem = re.sub(r"_recovered\b", " (recovered)", stem)
    stem = stem.replace("_", " ")
    return stem.strip(" ·") or name


CSS = """
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
       max-width: 980px; margin: 1.5em auto; padding: 0 1em; color: #222;
       line-height: 1.45; }
h1 { font-size: 1.7em; margin-bottom: 0.2em; }
.intro { color: #555; font-size: 0.95em; margin-bottom: 1.5em; }
.intro code { background: #f0f0f0; padding: 0 4px; border-radius: 3px; }
h2 { font-size: 1.15em; margin-top: 1.8em; padding-bottom: 4px;
     border-bottom: 1px solid #ddd; }
.note { color: #666; font-size: 0.9em; margin: 0.1em 0 0.8em 0; }
ul.report-list { list-style: none; padding: 0; margin: 0; }
ul.report-list li { padding: 4px 0; border-bottom: 1px dotted #eee; }
ul.report-list li:last-child { border-bottom: none; }
ul.report-list a { color: #1a4a8a; text-decoration: none; }
ul.report-list a:hover { text-decoration: underline; }
.fname { color: #888; font-size: 0.82em; font-family: ui-monospace,
         "SF Mono", Menlo, monospace; margin-left: 8px; }
.count { color: #888; font-size: 0.85em; font-weight: normal;
         margin-left: 6px; }
"""


def main() -> None:
    files = sorted(p.name for p in REPORTS_DIR.glob("*.html")
                   if p.name != "index.html")

    sections: list[tuple[str, str, list[str]]] = []
    assigned: set[str] = set()
    for prefix, title, desc in GROUPS:
        matches = [f for f in files if f.startswith(prefix)]
        if matches:
            sections.append((title, desc, matches))
            assigned.update(matches)

    other = [f for f in files if f not in assigned]
    if other:
        sections.append(("Other", "Reports that don't match a known prefix.",
                         other))

    parts: list[str] = [
        f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>510 final project — report index</title>
<style>{CSS}</style></head><body>
<h1>510 final project — report index</h1>
<div class="intro">
Master landing page for HTML reports under <code>reports/</code>.
Generated by <code>make_index.py</code>; re-run after producing any new
report to refresh the index.
</div>"""
    ]

    for title, desc, names in sections:
        parts.append(f'<h2>{esc(title)} <span class="count">'
                     f'({len(names)})</span></h2>')
        parts.append(f'<div class="note">{esc(desc)}</div>')
        parts.append('<ul class="report-list">')
        prefix = next((p for p, t, _ in GROUPS if t == title), "")
        for name in names:
            label = humanize(name, prefix) if prefix else name
            parts.append(
                f'<li><a href="{esc(name)}">{esc(label)}</a>'
                f'<span class="fname">{esc(name)}</span></li>'
            )
        parts.append('</ul>')

    parts.append('</body></html>')

    out = REPORTS_DIR / "index.html"
    out.write_text("\n".join(parts), encoding="utf-8")
    total = sum(len(names) for _, _, names in sections)
    print(f"wrote {out} ({total} reports across {len(sections)} sections)")


if __name__ == "__main__":
    main()
